// <auto-generated />
using System;
using BCXN.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BCXN.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211213104527_KySoTaiLieu_NgayTao")]
    partial class KySoTaiLieu_NgayTao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BCXN.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChucNangDefault")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("BCXN.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ChangePassWordDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DonViId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NhomQuyenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int?>("accountType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("BCXN.Models.BaoCao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChuKy")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int?>("DonViId")
                        .HasColumnType("int");

                    b.Property<int?>("LinhVucId")
                        .HasColumnType("int");

                    b.Property<int>("LoaiBaoCao")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("NguoiCapNhatId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<string>("SiteId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLieuId")
                        .HasColumnType("int");

                    b.Property<string>("TenBaoCao")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiHoatDong")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<string>("UrlLink")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("ViewId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViewName")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("BaoCao");
                });

            modelBuilder.Entity("BCXN.Models.ChucNang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChucNangChaId")
                        .HasColumnType("int");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LinkUrl")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ChucNang");
                });

            modelBuilder.Entity("BCXN.Models.ChucNangNhom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChucNangId")
                        .HasColumnType("int");

                    b.Property<string>("NhomQuyenId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChucNangNhom");
                });

            modelBuilder.Entity("BCXN.Models.DonVi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("DonViChaId")
                        .HasColumnType("int");

                    b.Property<string>("ERPIDDonVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERPMaChiNhanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERPMaCongTy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("LaPhongBan")
                        .HasColumnType("int");

                    b.Property<string>("MaDonVi")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("NguoiTaoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("TenDonVi")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DonVi");
                });

            modelBuilder.Entity("BCXN.Models.LichSuXacNhanBaoCao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BaoCaoId")
                        .HasColumnType("int");

                    b.Property<string>("FileBaoCao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<string>("NguoiTaoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianXacNhan")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TrangThaiDuLieu")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThaiXacNhan")
                        .HasColumnType("int");

                    b.Property<int>("YeuCauBaoCaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LichSuXacNhanBaoCao");
                });

            modelBuilder.Entity("BCXN.Models.LinhVucBaoCao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DaXoa")
                        .HasColumnType("int");

                    b.Property<int>("LinhVucChaId")
                        .HasColumnType("int");

                    b.Property<string>("NguoiTaoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("TrangThaiHoatDong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LinhVucBaoCao");
                });

            modelBuilder.Entity("BCXN.Models.NhomQuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("TenNhomQuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("NhomQuyen");
                });

            modelBuilder.Entity("BCXN.Models.Quyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("TenQuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Quyen");
                });

            modelBuilder.Entity("BCXN.Models.XacNhanBaoCao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BaoCaoId")
                        .HasColumnType("int");

                    b.Property<string>("FileBaoCao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SapXep")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianCapNhatDuLieu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianXacNhan")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TrangThaiDuLieu")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThaiXacNhan")
                        .HasColumnType("int");

                    b.Property<int>("YeuCauBaoCaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("XacNhanBaoCao");
                });

            modelBuilder.Entity("BCXN.Models.YeuCauBaoCao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChotSoLieu")
                        .HasColumnType("int");

                    b.Property<int?>("ChuKy")
                        .HasColumnType("int");

                    b.Property<int?>("DaXoa")
                        .HasColumnType("int");

                    b.Property<string>("FileBaoCaoHieuChinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HanHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LoaiChuKy")
                        .HasColumnType("int")
                        .HasMaxLength(10);

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int?>("Nam")
                        .HasColumnType("int");

                    b.Property<string>("NguoiTaoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("YeuCauBaoCao");
                });

            modelBuilder.Entity("Epayment.Models.ChiNhanhNganHang", b =>
                {
                    b.Property<Guid>("ChiNhanhNganHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("MaChiNhanhErp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NganHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenChiNhanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ChiNhanhNganHangId");

                    b.HasIndex("NganHangId");

                    b.ToTable("ChiNhanhNganHang");
                });

            modelBuilder.Entity("Epayment.Models.ChiTietGiayToHSTT", b =>
                {
                    b.Property<Guid>("ChiTietHoSoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileDinhKem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GiayToId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HoSoThanhToanHoSoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TrangThaiGiayTo")
                        .HasColumnType("int");

                    b.HasKey("ChiTietHoSoId");

                    b.HasIndex("GiayToId");

                    b.HasIndex("HoSoThanhToanHoSoId");

                    b.HasIndex("NguoiCapNhatId");

                    b.ToTable("ChiTietGiayToHSTT");
                });

            modelBuilder.Entity("Epayment.Models.ChiTietHachToan", b =>
                {
                    b.Property<Guid>("ChiTietHachToanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChungTuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TKCo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TKNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChiTietHachToanId");

                    b.HasIndex("ChungTuId");

                    b.ToTable("ChiTietHachToan");
                });

            modelBuilder.Entity("Epayment.Models.ChungTu", b =>
                {
                    b.Property<Guid>("ChungTuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CTGS_AP")
                        .HasColumnType("bit");

                    b.Property<bool>("CTGS_CM")
                        .HasColumnType("bit");

                    b.Property<bool>("CTGS_GL")
                        .HasColumnType("bit");

                    b.Property<int>("CapKy")
                        .HasColumnType("int");

                    b.Property<string>("ChungTuERPId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChiChuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DonViThanhToanId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("HoSoThanhToanHoSoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("KySoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoaiGiaoDich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiGiaoDichCha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiPhi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiTienTe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaChiNhanhChuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaChiNhanhNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNganHangChuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNganHangNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNuocChuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTinhTPChuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayLapChungTu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayYeuCauLapCT")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDuyetId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NguoiYeuCauLapId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDungTT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoChungTuERP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoTaiKhoanChuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoTaiKhoanNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenNganHangChuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNganHangNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiChuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTaiKhoanChuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTaiKhoanNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThaiCT")
                        .HasColumnType("int");

                    b.Property<decimal>("TyGia")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ChungTuId");

                    b.HasIndex("DonViThanhToanId");

                    b.HasIndex("HoSoThanhToanHoSoId");

                    b.HasIndex("NguoiDuyetId");

                    b.HasIndex("NguoiYeuCauLapId");

                    b.ToTable("ChungTu");
                });

            modelBuilder.Entity("Epayment.Models.ChungTuThanhToan", b =>
                {
                    b.Property<Guid>("ChungTuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HinhThucChi")
                        .HasColumnType("int");

                    b.Property<Guid?>("HoSoThanhToanHoSoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayLapCT")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiKyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NguoiLapId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoChungTu")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ChungTuId");

                    b.HasIndex("HoSoThanhToanHoSoId");

                    b.HasIndex("NguoiKyId");

                    b.HasIndex("NguoiLapId");

                    b.ToTable("ChungTuThanhToan");
                });

            modelBuilder.Entity("Epayment.Models.GiayTo", b =>
                {
                    b.Property<Guid>("GiayToId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KySo")
                        .HasColumnType("int");

                    b.Property<string>("MaGiayTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiTaoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nguon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenGiayTo")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("GiayToId");

                    b.ToTable("GiayTo");
                });

            modelBuilder.Entity("Epayment.Models.GiayToLoaiHoSo", b =>
                {
                    b.Property<Guid>("GiayToLoaiHoSoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BatBuoc")
                        .HasColumnType("int");

                    b.Property<Guid?>("GiayToId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LoaiHoSoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nguon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PheDuyetKySo")
                        .HasColumnType("int");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("GiayToLoaiHoSoId");

                    b.HasIndex("GiayToId");

                    b.HasIndex("LoaiHoSoId");

                    b.ToTable("GiayToLoaiHoSo");
                });

            modelBuilder.Entity("Epayment.Models.HoSoThanhToan", b =>
                {
                    b.Property<Guid>("HoSoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BoPhanCauIdId")
                        .HasColumnType("int");

                    b.Property<int>("BuocThucHien")
                        .HasColumnType("int");

                    b.Property<int>("CapKy")
                        .HasColumnType("int");

                    b.Property<int>("CoBanCung")
                        .HasColumnType("int");

                    b.Property<int>("CoHieuLuc")
                        .HasColumnType("int");

                    b.Property<int?>("DonViYeuCauId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HanThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int>("HinhThucChi")
                        .HasColumnType("int");

                    b.Property<int>("HinhThucTT")
                        .HasColumnType("int");

                    b.Property<int>("LanThanhToan")
                        .HasColumnType("int");

                    b.Property<Guid?>("LoaiHoSoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoaiTienTe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHoSo")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("MucDoUuTien")
                        .HasColumnType("int");

                    b.Property<int>("NamHoSo")
                        .HasColumnType("int");

                    b.Property<Guid?>("NganHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayLapCT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTiepNhan")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiTaoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NguoiThuHuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoTKThuHuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoTienThucTe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("TaiKhoanThuHuongTaiKhoanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TaiLieuGoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiLieuKy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHoSo")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("TenVietTat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenYeuCauThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThoiGianLuTru")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiHoSo")
                        .HasColumnType("int");

                    b.HasKey("HoSoId");

                    b.HasIndex("BoPhanCauIdId");

                    b.HasIndex("DonViYeuCauId");

                    b.HasIndex("LoaiHoSoId");

                    b.HasIndex("NganHangId");

                    b.HasIndex("NguoiTaoId");

                    b.HasIndex("TaiKhoanThuHuongTaiKhoanId");

                    b.ToTable("HoSoThanhToan");
                });

            modelBuilder.Entity("Epayment.Models.KySoChungTu", b =>
                {
                    b.Property<Guid>("KySoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CapKy")
                        .HasColumnType("int");

                    b.Property<Guid?>("ChungTuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DaKy")
                        .HasColumnType("bit");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("DuLieuKy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiKyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDungKy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KySoId");

                    b.HasIndex("ChungTuId");

                    b.HasIndex("NguoiKyId");

                    b.ToTable("KySoChungTu");
                });

            modelBuilder.Entity("Epayment.Models.KySoTaiLieu", b =>
                {
                    b.Property<Guid>("KySoTaiLieuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CapKy")
                        .HasColumnType("int");

                    b.Property<bool>("DaKy")
                        .HasColumnType("bit");

                    b.Property<bool?>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<Guid?>("HoSoThanhToanHoSoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiKyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDungKy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiLieuGoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiLieuKy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KySoTaiLieuId");

                    b.HasIndex("HoSoThanhToanHoSoId");

                    b.HasIndex("NguoiKyId");

                    b.ToTable("KySoTaiLieu");
                });

            modelBuilder.Entity("Epayment.Models.LichSuChiTietGiayTo", b =>
                {
                    b.Property<Guid>("ChiTietHoSoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileDinhKem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GiayToId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HoSoThanhToanHoSoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TrangThaiGiayTo")
                        .HasColumnType("int");

                    b.HasKey("ChiTietHoSoId");

                    b.HasIndex("GiayToId");

                    b.HasIndex("HoSoThanhToanHoSoId");

                    b.HasIndex("NguoiCapNhatId");

                    b.ToTable("LichSuChiTietGiayTo");
                });

            modelBuilder.Entity("Epayment.Models.LichSuHoSoTT", b =>
                {
                    b.Property<Guid>("LichSuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BoPhanCauId")
                        .HasColumnType("int");

                    b.Property<int>("BuocThucHien")
                        .HasColumnType("int");

                    b.Property<int?>("DonViYeuCauId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HanThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int>("HinhThucTT")
                        .HasColumnType("int");

                    b.Property<Guid?>("HoSoThanhToanHoSoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LoaiHoSoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaHoSo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MucDoUuTien")
                        .HasColumnType("int");

                    b.Property<int>("NamHoSo")
                        .HasColumnType("int");

                    b.Property<Guid>("NganHangThuHuong")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayLapCT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTiepNhan")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NguoiThuHuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoTKThuHuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoTienThucTe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenHoSo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThoiGianLuTru")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiHoSo")
                        .HasColumnType("int");

                    b.HasKey("LichSuId");

                    b.HasIndex("BoPhanCauId");

                    b.HasIndex("DonViYeuCauId");

                    b.HasIndex("HoSoThanhToanHoSoId");

                    b.HasIndex("LoaiHoSoId");

                    b.HasIndex("NguoiCapNhatId");

                    b.ToTable("LichSuHoSoTT");
                });

            modelBuilder.Entity("Epayment.Models.LoaiHoSo", b =>
                {
                    b.Property<Guid>("LoaiHoSoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DaXoa")
                        .HasColumnType("int");

                    b.Property<string>("MaLoaiHoSo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenLoaiHoSo")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("LoaiHoSoId");

                    b.ToTable("LoaiHoSo");
                });

            modelBuilder.Entity("Epayment.Models.LuongPheDuyet", b =>
                {
                    b.Property<Guid>("BuocThucHienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChuyenSangERP")
                        .HasColumnType("int");

                    b.Property<int>("CoThamTra")
                        .HasColumnType("int");

                    b.Property<int>("DaXoa")
                        .HasColumnType("int");

                    b.Property<Guid?>("LoaiHoSoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenBuoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<Guid?>("TrangThaiHoSoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VaiTroId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BuocThucHienId");

                    b.HasIndex("LoaiHoSoId");

                    b.HasIndex("TrangThaiHoSoId");

                    b.HasIndex("VaiTroId");

                    b.ToTable("LuongPheDuyet");
                });

            modelBuilder.Entity("Epayment.Models.NganHang", b =>
                {
                    b.Property<Guid>("NganHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNganHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNganHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenVietTat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTiepNhan")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThaiTiepNhan")
                        .HasColumnType("int");

                    b.HasKey("NganHangId");

                    b.ToTable("NganHang");
                });

            modelBuilder.Entity("Epayment.Models.NguoiThuHuong", b =>
                {
                    b.Property<Guid>("NguoiThuHuongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HinhThucTT")
                        .HasColumnType("int");

                    b.Property<Guid?>("HoSoThanhToanHoSoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NganHangThuHuongNganHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoTKThuHuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTienThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenNguoiThuHuong")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NguoiThuHuongId");

                    b.HasIndex("HoSoThanhToanHoSoId");

                    b.HasIndex("NganHangThuHuongNganHangId");

                    b.ToTable("NguoiThuHuong");
                });

            modelBuilder.Entity("Epayment.Models.PhanCongXuLy", b =>
                {
                    b.Property<Guid>("PhanCongXuLyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<Guid?>("HoSoThanhToanHoSoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NguoiXuLyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ThoiGianGiao")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThaiTiepNhan")
                        .HasColumnType("int");

                    b.HasKey("PhanCongXuLyId");

                    b.HasIndex("HoSoThanhToanHoSoId");

                    b.HasIndex("NguoiXuLyId");

                    b.ToTable("PhanCongXuLy");
                });

            modelBuilder.Entity("Epayment.Models.PheDuyetHoSoTT", b =>
                {
                    b.Property<Guid>("PheDuyetHoSoTTId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuocThucHien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("HoSoThanhToanHoSoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayThucHien")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiThucHienId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiHoSo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiPheDuyet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PheDuyetHoSoTTId");

                    b.HasIndex("HoSoThanhToanHoSoId");

                    b.HasIndex("NguoiThucHienId");

                    b.ToTable("PheDuyetHoSoTT");
                });

            modelBuilder.Entity("Epayment.Models.TaiKhoanNganHang", b =>
                {
                    b.Property<Guid>("TaiKhoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChiNhanhNganHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DonViId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NganHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoTaiKhoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTaiKhoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("TaiKhoanId");

                    b.HasIndex("ChiNhanhNganHangId");

                    b.HasIndex("DonViId");

                    b.HasIndex("NganHangId");

                    b.ToTable("TaiKhoanNganHang");
                });

            modelBuilder.Entity("Epayment.Models.TrangThaiHoSo", b =>
                {
                    b.Property<Guid>("TrangThaiHoSoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GiaTri")
                        .HasColumnType("int");

                    b.Property<string>("TenTrangThaiHoSo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("TrangThaiHoSoId");

                    b.ToTable("TrangThaiHoSo");
                });

            modelBuilder.Entity("Epayment.Models.VaiTro", b =>
                {
                    b.Property<Guid>("VaiTroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenVaiTro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VaiTroId");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("Epayment.Models.YeuCauChiTien", b =>
                {
                    b.Property<Guid>("YeuCauChiTienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChuKy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ChungTuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaKetQuaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NganHangChiNganHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NganHangThuHuongNganHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayYeuCauChi")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiThuHuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiYeuCauChiId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("RequestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SoTienTT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TaiKhoanChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanThuHuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianChi")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThaiChi")
                        .HasColumnType("int");

                    b.HasKey("YeuCauChiTienId");

                    b.HasIndex("ChungTuId");

                    b.HasIndex("NganHangChiNganHangId");

                    b.HasIndex("NganHangThuHuongNganHangId");

                    b.HasIndex("NguoiYeuCauChiId");

                    b.ToTable("YeuCauChiTien");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BCXN.Models.ApplicationUser", b =>
                {
                    b.OwnsMany("Epayment.Models.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("ApplicationUserId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime2");

                            b1.Property<string>("CreatedByIp")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("datetime2");

                            b1.Property<string>("ReplacedByToken")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("Revoked")
                                .HasColumnType("datetime2");

                            b1.Property<string>("RevokedByIp")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Token")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("ApplicationUserId");

                            b1.ToTable("RefreshToken");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationUserId");
                        });
                });

            modelBuilder.Entity("Epayment.Models.ChiNhanhNganHang", b =>
                {
                    b.HasOne("Epayment.Models.NganHang", "NganHang")
                        .WithMany()
                        .HasForeignKey("NganHangId");
                });

            modelBuilder.Entity("Epayment.Models.ChiTietGiayToHSTT", b =>
                {
                    b.HasOne("Epayment.Models.GiayTo", "GiayTo")
                        .WithMany()
                        .HasForeignKey("GiayToId");

                    b.HasOne("Epayment.Models.HoSoThanhToan", "HoSoThanhToan")
                        .WithMany()
                        .HasForeignKey("HoSoThanhToanHoSoId");

                    b.HasOne("BCXN.Models.ApplicationUser", "NguoiCapNhat")
                        .WithMany()
                        .HasForeignKey("NguoiCapNhatId");
                });

            modelBuilder.Entity("Epayment.Models.ChiTietHachToan", b =>
                {
                    b.HasOne("Epayment.Models.ChungTu", "ChungTu")
                        .WithMany()
                        .HasForeignKey("ChungTuId");
                });

            modelBuilder.Entity("Epayment.Models.ChungTu", b =>
                {
                    b.HasOne("BCXN.Models.DonVi", "DonViThanhToan")
                        .WithMany()
                        .HasForeignKey("DonViThanhToanId");

                    b.HasOne("Epayment.Models.HoSoThanhToan", "HoSoThanhToan")
                        .WithMany()
                        .HasForeignKey("HoSoThanhToanHoSoId");

                    b.HasOne("BCXN.Models.ApplicationUser", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("NguoiDuyetId");

                    b.HasOne("BCXN.Models.ApplicationUser", "NguoiYeuCauLap")
                        .WithMany()
                        .HasForeignKey("NguoiYeuCauLapId");
                });

            modelBuilder.Entity("Epayment.Models.ChungTuThanhToan", b =>
                {
                    b.HasOne("Epayment.Models.HoSoThanhToan", "HoSoThanhToan")
                        .WithMany()
                        .HasForeignKey("HoSoThanhToanHoSoId");

                    b.HasOne("BCXN.Models.ApplicationUser", "NguoiKy")
                        .WithMany()
                        .HasForeignKey("NguoiKyId");

                    b.HasOne("BCXN.Models.ApplicationUser", "NguoiLap")
                        .WithMany()
                        .HasForeignKey("NguoiLapId");
                });

            modelBuilder.Entity("Epayment.Models.GiayToLoaiHoSo", b =>
                {
                    b.HasOne("Epayment.Models.GiayTo", "GiayTo")
                        .WithMany()
                        .HasForeignKey("GiayToId");

                    b.HasOne("Epayment.Models.LoaiHoSo", "LoaiHoSo")
                        .WithMany()
                        .HasForeignKey("LoaiHoSoId");
                });

            modelBuilder.Entity("Epayment.Models.HoSoThanhToan", b =>
                {
                    b.HasOne("BCXN.Models.DonVi", "BoPhanCauId")
                        .WithMany()
                        .HasForeignKey("BoPhanCauIdId");

                    b.HasOne("BCXN.Models.DonVi", "DonViYeuCau")
                        .WithMany()
                        .HasForeignKey("DonViYeuCauId");

                    b.HasOne("Epayment.Models.LoaiHoSo", "LoaiHoSo")
                        .WithMany()
                        .HasForeignKey("LoaiHoSoId");

                    b.HasOne("Epayment.Models.NganHang", "NganHang")
                        .WithMany()
                        .HasForeignKey("NganHangId");

                    b.HasOne("BCXN.Models.ApplicationUser", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId");

                    b.HasOne("Epayment.Models.TaiKhoanNganHang", "TaiKhoanThuHuong")
                        .WithMany()
                        .HasForeignKey("TaiKhoanThuHuongTaiKhoanId");
                });

            modelBuilder.Entity("Epayment.Models.KySoChungTu", b =>
                {
                    b.HasOne("Epayment.Models.ChungTu", "ChungTu")
                        .WithMany()
                        .HasForeignKey("ChungTuId");

                    b.HasOne("BCXN.Models.ApplicationUser", "NguoiKy")
                        .WithMany()
                        .HasForeignKey("NguoiKyId");
                });

            modelBuilder.Entity("Epayment.Models.KySoTaiLieu", b =>
                {
                    b.HasOne("Epayment.Models.HoSoThanhToan", "HoSoThanhToan")
                        .WithMany()
                        .HasForeignKey("HoSoThanhToanHoSoId");

                    b.HasOne("BCXN.Models.ApplicationUser", "NguoiKy")
                        .WithMany()
                        .HasForeignKey("NguoiKyId");
                });

            modelBuilder.Entity("Epayment.Models.LichSuChiTietGiayTo", b =>
                {
                    b.HasOne("Epayment.Models.GiayTo", "GiayTo")
                        .WithMany()
                        .HasForeignKey("GiayToId");

                    b.HasOne("Epayment.Models.HoSoThanhToan", "HoSoThanhToan")
                        .WithMany()
                        .HasForeignKey("HoSoThanhToanHoSoId");

                    b.HasOne("BCXN.Models.ApplicationUser", "NguoiCapNhat")
                        .WithMany()
                        .HasForeignKey("NguoiCapNhatId");
                });

            modelBuilder.Entity("Epayment.Models.LichSuHoSoTT", b =>
                {
                    b.HasOne("BCXN.Models.DonVi", "BoPhanCau")
                        .WithMany()
                        .HasForeignKey("BoPhanCauId");

                    b.HasOne("BCXN.Models.DonVi", "DonViYeuCau")
                        .WithMany()
                        .HasForeignKey("DonViYeuCauId");

                    b.HasOne("Epayment.Models.HoSoThanhToan", "HoSoThanhToan")
                        .WithMany()
                        .HasForeignKey("HoSoThanhToanHoSoId");

                    b.HasOne("Epayment.Models.LoaiHoSo", "LoaiHoSo")
                        .WithMany()
                        .HasForeignKey("LoaiHoSoId");

                    b.HasOne("BCXN.Models.ApplicationUser", "NguoiCapNhat")
                        .WithMany()
                        .HasForeignKey("NguoiCapNhatId");
                });

            modelBuilder.Entity("Epayment.Models.LuongPheDuyet", b =>
                {
                    b.HasOne("Epayment.Models.LoaiHoSo", "LoaiHoSo")
                        .WithMany()
                        .HasForeignKey("LoaiHoSoId");

                    b.HasOne("Epayment.Models.TrangThaiHoSo", "TrangThaiHoSo")
                        .WithMany()
                        .HasForeignKey("TrangThaiHoSoId");

                    b.HasOne("Epayment.Models.VaiTro", "VaiTro")
                        .WithMany()
                        .HasForeignKey("VaiTroId");
                });

            modelBuilder.Entity("Epayment.Models.NguoiThuHuong", b =>
                {
                    b.HasOne("Epayment.Models.HoSoThanhToan", "HoSoThanhToan")
                        .WithMany()
                        .HasForeignKey("HoSoThanhToanHoSoId");

                    b.HasOne("Epayment.Models.NganHang", "NganHangThuHuong")
                        .WithMany()
                        .HasForeignKey("NganHangThuHuongNganHangId");
                });

            modelBuilder.Entity("Epayment.Models.PhanCongXuLy", b =>
                {
                    b.HasOne("Epayment.Models.HoSoThanhToan", "HoSoThanhToan")
                        .WithMany()
                        .HasForeignKey("HoSoThanhToanHoSoId");

                    b.HasOne("BCXN.Models.ApplicationUser", "NguoiXuLy")
                        .WithMany()
                        .HasForeignKey("NguoiXuLyId");
                });

            modelBuilder.Entity("Epayment.Models.PheDuyetHoSoTT", b =>
                {
                    b.HasOne("Epayment.Models.HoSoThanhToan", "HoSoThanhToan")
                        .WithMany()
                        .HasForeignKey("HoSoThanhToanHoSoId");

                    b.HasOne("BCXN.Models.ApplicationUser", "NguoiThucHien")
                        .WithMany()
                        .HasForeignKey("NguoiThucHienId");
                });

            modelBuilder.Entity("Epayment.Models.TaiKhoanNganHang", b =>
                {
                    b.HasOne("Epayment.Models.ChiNhanhNganHang", "ChiNhanhNganHang")
                        .WithMany()
                        .HasForeignKey("ChiNhanhNganHangId");

                    b.HasOne("BCXN.Models.DonVi", "DonVi")
                        .WithMany()
                        .HasForeignKey("DonViId");

                    b.HasOne("Epayment.Models.NganHang", "NganHang")
                        .WithMany()
                        .HasForeignKey("NganHangId");
                });

            modelBuilder.Entity("Epayment.Models.YeuCauChiTien", b =>
                {
                    b.HasOne("Epayment.Models.ChungTu", "ChungTu")
                        .WithMany()
                        .HasForeignKey("ChungTuId");

                    b.HasOne("Epayment.Models.NganHang", "NganHangChi")
                        .WithMany()
                        .HasForeignKey("NganHangChiNganHangId");

                    b.HasOne("Epayment.Models.NganHang", "NganHangThuHuong")
                        .WithMany()
                        .HasForeignKey("NganHangThuHuongNganHangId");

                    b.HasOne("BCXN.Models.ApplicationUser", "NguoiYeuCauChi")
                        .WithMany()
                        .HasForeignKey("NguoiYeuCauChiId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("BCXN.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BCXN.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BCXN.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("BCXN.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BCXN.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BCXN.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
